<?php
/**
 * CustomFields
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * CustomFields Class Doc Comment
 *
 * @category    Class
 * @description Custom Fields PDF form
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CustomFields implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'image_custom_fields' => '\Swagger\Client\Model\ImageCustomField[]',
        'text_custom_fields' => '\Swagger\Client\Model\TextCustomField[]'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'image_custom_fields' => 'imageCustomFields',
        'text_custom_fields' => 'textCustomFields'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'image_custom_fields' => 'setImageCustomFields',
        'text_custom_fields' => 'setTextCustomFields'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'image_custom_fields' => 'getImageCustomFields',
        'text_custom_fields' => 'getTextCustomFields'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $image_custom_fields Custom picture field
      * @var \Swagger\Client\Model\ImageCustomField[]
      */
    protected $image_custom_fields;
    
    /**
      * $text_custom_fields \u5B57\u6BB5\u4E32\u5B57\u6BB5
      * @var \Swagger\Client\Model\TextCustomField[]
      */
    protected $text_custom_fields;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->image_custom_fields = $data["image_custom_fields"];
            $this->text_custom_fields = $data["text_custom_fields"];
        }
    }
    
    /**
     * Gets image_custom_fields
     * @return \Swagger\Client\Model\ImageCustomField[]
     */
    public function getImageCustomFields()
    {
        return $this->image_custom_fields;
    }
  
    /**
     * Sets image_custom_fields
     * @param \Swagger\Client\Model\ImageCustomField[] $image_custom_fields Custom picture field
     * @return $this
     */
    public function setImageCustomFields($image_custom_fields)
    {
        
        $this->image_custom_fields = $image_custom_fields;
        return $this;
    }
    
    /**
     * Gets text_custom_fields
     * @return \Swagger\Client\Model\TextCustomField[]
     */
    public function getTextCustomFields()
    {
        return $this->text_custom_fields;
    }
  
    /**
     * Sets text_custom_fields
     * @param \Swagger\Client\Model\TextCustomField[] $text_custom_fields \u5B57\u6BB5\u4E32\u5B57\u6BB5
     * @return $this
     */
    public function setTextCustomFields($text_custom_fields)
    {
        
        $this->text_custom_fields = $text_custom_fields;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
