<?php
/**
 * DocumentDefinition
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * DocumentDefinition Class Doc Comment
 *
 * @category    Class
 * @description \u7B7E\u7F72\u6587\u6863\u5B9A\u4E49
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DocumentDefinition implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'app' => '\Swagger\Client\Model\App',
        'custom_fields' => '\Swagger\Client\Model\CustomFields',
        'documents' => '\Swagger\Client\Model\Document[]',
        'extra_recipients' => '\Swagger\Client\Model\ExtraRecipients',
        'id_auth' => '\Swagger\Client\Model\IdAuth',
        'signers' => '\Swagger\Client\Model\Signers',
        'template_id' => 'string'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'app' => 'app',
        'custom_fields' => 'customFields',
        'documents' => 'documents',
        'extra_recipients' => 'extraRecipients',
        'id_auth' => 'idAuth',
        'signers' => 'signers',
        'template_id' => 'templateId'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'app' => 'setApp',
        'custom_fields' => 'setCustomFields',
        'documents' => 'setDocuments',
        'extra_recipients' => 'setExtraRecipients',
        'id_auth' => 'setIdAuth',
        'signers' => 'setSigners',
        'template_id' => 'setTemplateId'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'app' => 'getApp',
        'custom_fields' => 'getCustomFields',
        'documents' => 'getDocuments',
        'extra_recipients' => 'getExtraRecipients',
        'id_auth' => 'getIdAuth',
        'signers' => 'getSigners',
        'template_id' => 'getTemplateId'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $app Application configuration
      * @var \Swagger\Client\Model\App
      */
    protected $app;
    
    /**
      * $custom_fields \u81EA\u5B9A\u4E49\u5B57\u6BB5
      * @var \Swagger\Client\Model\CustomFields
      */
    protected $custom_fields;
    
    /**
      * $documents \u5F85\u7B7E\u7F72\u7684\u6587\u6863\u5217\u8868
      * @var \Swagger\Client\Model\Document[]
      */
    protected $documents;
    
    /**
      * $extra_recipients \u5176\u5B83\u63A5\u6536\u4EBA
      * @var \Swagger\Client\Model\ExtraRecipients
      */
    protected $extra_recipients;
    
    /**
      * $id_auth Signature authentication
      * @var \Swagger\Client\Model\IdAuth
      */
    protected $id_auth;
    
    /**
      * $signers \u7B7E\u7F72\u4EBA
      * @var \Swagger\Client\Model\Signers
      */
    protected $signers;
    
    /**
      * $template_id Custom template number
      * @var string
      */
    protected $template_id;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->app = $data["app"];
            $this->custom_fields = $data["custom_fields"];
            $this->documents = $data["documents"];
            $this->extra_recipients = $data["extra_recipients"];
            $this->id_auth = $data["id_auth"];
            $this->signers = $data["signers"];
            $this->template_id = $data["template_id"];
        }
    }
    
    /**
     * Gets app
     * @return \Swagger\Client\Model\App
     */
    public function getApp()
    {
        return $this->app;
    }
  
    /**
     * Sets app
     * @param \Swagger\Client\Model\App $app Application configuration
     * @return $this
     */
    public function setApp($app)
    {
        
        $this->app = $app;
        return $this;
    }
    
    /**
     * Gets custom_fields
     * @return \Swagger\Client\Model\CustomFields
     */
    public function getCustomFields()
    {
        return $this->custom_fields;
    }
  
    /**
     * Sets custom_fields
     * @param \Swagger\Client\Model\CustomFields $custom_fields \u81EA\u5B9A\u4E49\u5B57\u6BB5
     * @return $this
     */
    public function setCustomFields($custom_fields)
    {
        
        $this->custom_fields = $custom_fields;
        return $this;
    }
    
    /**
     * Gets documents
     * @return \Swagger\Client\Model\Document[]
     */
    public function getDocuments()
    {
        return $this->documents;
    }
  
    /**
     * Sets documents
     * @param \Swagger\Client\Model\Document[] $documents \u5F85\u7B7E\u7F72\u7684\u6587\u6863\u5217\u8868
     * @return $this
     */
    public function setDocuments($documents)
    {
        
        $this->documents = $documents;
        return $this;
    }
    
    /**
     * Gets extra_recipients
     * @return \Swagger\Client\Model\ExtraRecipients
     */
    public function getExtraRecipients()
    {
        return $this->extra_recipients;
    }
  
    /**
     * Sets extra_recipients
     * @param \Swagger\Client\Model\ExtraRecipients $extra_recipients \u5176\u5B83\u63A5\u6536\u4EBA
     * @return $this
     */
    public function setExtraRecipients($extra_recipients)
    {
        
        $this->extra_recipients = $extra_recipients;
        return $this;
    }
    
    /**
     * Gets id_auth
     * @return \Swagger\Client\Model\IdAuth
     */
    public function getIdAuth()
    {
        return $this->id_auth;
    }
  
    /**
     * Sets id_auth
     * @param \Swagger\Client\Model\IdAuth $id_auth Signature authentication
     * @return $this
     */
    public function setIdAuth($id_auth)
    {
        
        $this->id_auth = $id_auth;
        return $this;
    }
    
    /**
     * Gets signers
     * @return \Swagger\Client\Model\Signers
     */
    public function getSigners()
    {
        return $this->signers;
    }
  
    /**
     * Sets signers
     * @param \Swagger\Client\Model\Signers $signers \u7B7E\u7F72\u4EBA
     * @return $this
     */
    public function setSigners($signers)
    {
        
        $this->signers = $signers;
        return $this;
    }
    
    /**
     * Gets template_id
     * @return string
     */
    public function getTemplateId()
    {
        return $this->template_id;
    }
  
    /**
     * Sets template_id
     * @param string $template_id Custom template number
     * @return $this
     */
    public function setTemplateId($template_id)
    {
        
        $this->template_id = $template_id;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
