<?php
/**
 * ExtraRecipients
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * ExtraRecipients Class Doc Comment
 *
 * @category    Class
 * @description \u5176\u5B83\u63A5\u6536\u4EBA
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExtraRecipients implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'emai_recipients' => '\Swagger\Client\Model\EmailRecipient[]',
        'sms_recipients' => '\Swagger\Client\Model\SmsRecipient[]',
        'wechat_recipients' => '\Swagger\Client\Model\WechatRecipient[]'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'emai_recipients' => 'emaiRecipients',
        'sms_recipients' => 'smsRecipients',
        'wechat_recipients' => 'wechatRecipients'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'emai_recipients' => 'setEmaiRecipients',
        'sms_recipients' => 'setSmsRecipients',
        'wechat_recipients' => 'setWechatRecipients'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'emai_recipients' => 'getEmaiRecipients',
        'sms_recipients' => 'getSmsRecipients',
        'wechat_recipients' => 'getWechatRecipients'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $emai_recipients \u6240\u6709\u90AE\u4EF6\u63A5\u6536\u8005
      * @var \Swagger\Client\Model\EmailRecipient[]
      */
    protected $emai_recipients;
    
    /**
      * $sms_recipients \u6240\u6709\u77ED\u4FE1\u63A5\u6536\u8005
      * @var \Swagger\Client\Model\SmsRecipient[]
      */
    protected $sms_recipients;
    
    /**
      * $wechat_recipients \u6240\u6709\u5FAE\u4FE1\u63A5\u6536\u8005
      * @var \Swagger\Client\Model\WechatRecipient[]
      */
    protected $wechat_recipients;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->emai_recipients = $data["emai_recipients"];
            $this->sms_recipients = $data["sms_recipients"];
            $this->wechat_recipients = $data["wechat_recipients"];
        }
    }
    
    /**
     * Gets emai_recipients
     * @return \Swagger\Client\Model\EmailRecipient[]
     */
    public function getEmaiRecipients()
    {
        return $this->emai_recipients;
    }
  
    /**
     * Sets emai_recipients
     * @param \Swagger\Client\Model\EmailRecipient[] $emai_recipients \u6240\u6709\u90AE\u4EF6\u63A5\u6536\u8005
     * @return $this
     */
    public function setEmaiRecipients($emai_recipients)
    {
        
        $this->emai_recipients = $emai_recipients;
        return $this;
    }
    
    /**
     * Gets sms_recipients
     * @return \Swagger\Client\Model\SmsRecipient[]
     */
    public function getSmsRecipients()
    {
        return $this->sms_recipients;
    }
  
    /**
     * Sets sms_recipients
     * @param \Swagger\Client\Model\SmsRecipient[] $sms_recipients \u6240\u6709\u77ED\u4FE1\u63A5\u6536\u8005
     * @return $this
     */
    public function setSmsRecipients($sms_recipients)
    {
        
        $this->sms_recipients = $sms_recipients;
        return $this;
    }
    
    /**
     * Gets wechat_recipients
     * @return \Swagger\Client\Model\WechatRecipient[]
     */
    public function getWechatRecipients()
    {
        return $this->wechat_recipients;
    }
  
    /**
     * Sets wechat_recipients
     * @param \Swagger\Client\Model\WechatRecipient[] $wechat_recipients \u6240\u6709\u5FAE\u4FE1\u63A5\u6536\u8005
     * @return $this
     */
    public function setWechatRecipients($wechat_recipients)
    {
        
        $this->wechat_recipients = $wechat_recipients;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
