<?php
/**
 * ImageCustomField
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * ImageCustomField Class Doc Comment
 *
 * @category    Class
 * @description Custom fields for image type
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ImageCustomField implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'field_id' => 'string',
        'image_base64' => 'string',
        'seal_id' => 'string',
        'signature_id' => 'string'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'field_id' => 'fieldId',
        'image_base64' => 'imageBase64',
        'seal_id' => 'sealId',
        'signature_id' => 'signatureId'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'field_id' => 'setFieldId',
        'image_base64' => 'setImageBase64',
        'seal_id' => 'setSealId',
        'signature_id' => 'setSignatureId'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'field_id' => 'getFieldId',
        'image_base64' => 'getImageBase64',
        'seal_id' => 'getSealId',
        'signature_id' => 'getSignatureId'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $field_id Custom field id
      * @var string
      */
    protected $field_id;
    
    /**
      * $image_base64 Base64 image file format
      * @var string
      */
    protected $image_base64;
    
    /**
      * $seal_id user seal ID
      * @var string
      */
    protected $seal_id;
    
    /**
      * $signature_id user signature ID
      * @var string
      */
    protected $signature_id;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->field_id = $data["field_id"];
            $this->image_base64 = $data["image_base64"];
            $this->seal_id = $data["seal_id"];
            $this->signature_id = $data["signature_id"];
        }
    }
    
    /**
     * Gets field_id
     * @return string
     */
    public function getFieldId()
    {
        return $this->field_id;
    }
  
    /**
     * Sets field_id
     * @param string $field_id Custom field id
     * @return $this
     */
    public function setFieldId($field_id)
    {
        
        $this->field_id = $field_id;
        return $this;
    }
    
    /**
     * Gets image_base64
     * @return string
     */
    public function getImageBase64()
    {
        return $this->image_base64;
    }
  
    /**
     * Sets image_base64
     * @param string $image_base64 Base64 image file format
     * @return $this
     */
    public function setImageBase64($image_base64)
    {
        
        $this->image_base64 = $image_base64;
        return $this;
    }
    
    /**
     * Gets seal_id
     * @return string
     */
    public function getSealId()
    {
        return $this->seal_id;
    }
  
    /**
     * Sets seal_id
     * @param string $seal_id user seal ID
     * @return $this
     */
    public function setSealId($seal_id)
    {
        
        $this->seal_id = $seal_id;
        return $this;
    }
    
    /**
     * Gets signature_id
     * @return string
     */
    public function getSignatureId()
    {
        return $this->signature_id;
    }
  
    /**
     * Sets signature_id
     * @param string $signature_id user signature ID
     * @return $this
     */
    public function setSignatureId($signature_id)
    {
        
        $this->signature_id = $signature_id;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
