<?php
/**
 * Personal
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * Personal Class Doc Comment
 *
 * @category    Class
 * @description \u4E2A\u4EBA\u4FE1\u606F
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Personal implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'bank_account_number' => 'string',
        'bank_location' => 'string',
        'bank_name' => 'string',
        'email_notice' => 'string',
        'linksign_user_id' => 'string',
        'person_email' => 'string',
        'person_idcard_image_base64' => 'string',
        'person_idcard_number' => 'string',
        'person_idcard_type' => 'string',
        'person_name' => 'string',
        'person_org_name' => 'string',
        'person_phone' => 'string',
        'recipient_index' => 'string',
        'signature_image_base64' => 'string',
        'sms_notice' => 'string'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'bank_account_number' => 'bankAccountNumber',
        'bank_location' => 'bankLocation',
        'bank_name' => 'bankName',
        'email_notice' => 'emailNotice',
        'linksign_user_id' => 'linksignUserId',
        'person_email' => 'personEmail',
        'person_idcard_image_base64' => 'personIdcardImageBase64',
        'person_idcard_number' => 'personIdcardNumber',
        'person_idcard_type' => 'personIdcardType',
        'person_name' => 'personName',
        'person_org_name' => 'personOrgName',
        'person_phone' => 'personPhone',
        'recipient_index' => 'recipientIndex',
        'signature_image_base64' => 'signatureImageBase64',
        'sms_notice' => 'smsNotice'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'bank_account_number' => 'setBankAccountNumber',
        'bank_location' => 'setBankLocation',
        'bank_name' => 'setBankName',
        'email_notice' => 'setEmailNotice',
        'linksign_user_id' => 'setLinksignUserId',
        'person_email' => 'setPersonEmail',
        'person_idcard_image_base64' => 'setPersonIdcardImageBase64',
        'person_idcard_number' => 'setPersonIdcardNumber',
        'person_idcard_type' => 'setPersonIdcardType',
        'person_name' => 'setPersonName',
        'person_org_name' => 'setPersonOrgName',
        'person_phone' => 'setPersonPhone',
        'recipient_index' => 'setRecipientIndex',
        'signature_image_base64' => 'setSignatureImageBase64',
        'sms_notice' => 'setSmsNotice'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'bank_account_number' => 'getBankAccountNumber',
        'bank_location' => 'getBankLocation',
        'bank_name' => 'getBankName',
        'email_notice' => 'getEmailNotice',
        'linksign_user_id' => 'getLinksignUserId',
        'person_email' => 'getPersonEmail',
        'person_idcard_image_base64' => 'getPersonIdcardImageBase64',
        'person_idcard_number' => 'getPersonIdcardNumber',
        'person_idcard_type' => 'getPersonIdcardType',
        'person_name' => 'getPersonName',
        'person_org_name' => 'getPersonOrgName',
        'person_phone' => 'getPersonPhone',
        'recipient_index' => 'getRecipientIndex',
        'signature_image_base64' => 'getSignatureImageBase64',
        'sms_notice' => 'getSmsNotice'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $bank_account_number 
      * @var string
      */
    protected $bank_account_number;
    
    /**
      * $bank_location 
      * @var string
      */
    protected $bank_location;
    
    /**
      * $bank_name 
      * @var string
      */
    protected $bank_name;
    
    /**
      * $email_notice \u662F\u5426\u90AE\u4EF6\u901A\u77E5\u7B7E\u7F72\u4EBA(y/n)
      * @var string
      */
    protected $email_notice;
    
    /**
      * $linksign_user_id \u9886\u7B7E\u7CFB\u7EDF\u7528\u6237\u7F16\u53F7
      * @var string
      */
    protected $linksign_user_id;
    
    /**
      * $person_email 
      * @var string
      */
    protected $person_email;
    
    /**
      * $person_idcard_image_base64 
      * @var string
      */
    protected $person_idcard_image_base64;
    
    /**
      * $person_idcard_number 
      * @var string
      */
    protected $person_idcard_number;
    
    /**
      * $person_idcard_type 
      * @var string
      */
    protected $person_idcard_type;
    
    /**
      * $person_name 
      * @var string
      */
    protected $person_name;
    
    /**
      * $person_org_name 
      * @var string
      */
    protected $person_org_name;
    
    /**
      * $person_phone 
      * @var string
      */
    protected $person_phone;
    
    /**
      * $recipient_index \u4E2A\u4EBA\u7D22\u5F15
      * @var string
      */
    protected $recipient_index;
    
    /**
      * $signature_image_base64 The original signature (scan)
      * @var string
      */
    protected $signature_image_base64;
    
    /**
      * $sms_notice \u662F\u5426\u77ED\u4FE1\u901A\u77E5\u7B7E\u7F72\u4EBA(y/n)
      * @var string
      */
    protected $sms_notice;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->bank_account_number = $data["bank_account_number"];
            $this->bank_location = $data["bank_location"];
            $this->bank_name = $data["bank_name"];
            $this->email_notice = $data["email_notice"];
            $this->linksign_user_id = $data["linksign_user_id"];
            $this->person_email = $data["person_email"];
            $this->person_idcard_image_base64 = $data["person_idcard_image_base64"];
            $this->person_idcard_number = $data["person_idcard_number"];
            $this->person_idcard_type = $data["person_idcard_type"];
            $this->person_name = $data["person_name"];
            $this->person_org_name = $data["person_org_name"];
            $this->person_phone = $data["person_phone"];
            $this->recipient_index = $data["recipient_index"];
            $this->signature_image_base64 = $data["signature_image_base64"];
            $this->sms_notice = $data["sms_notice"];
        }
    }
    
    /**
     * Gets bank_account_number
     * @return string
     */
    public function getBankAccountNumber()
    {
        return $this->bank_account_number;
    }
  
    /**
     * Sets bank_account_number
     * @param string $bank_account_number 
     * @return $this
     */
    public function setBankAccountNumber($bank_account_number)
    {
        
        $this->bank_account_number = $bank_account_number;
        return $this;
    }
    
    /**
     * Gets bank_location
     * @return string
     */
    public function getBankLocation()
    {
        return $this->bank_location;
    }
  
    /**
     * Sets bank_location
     * @param string $bank_location 
     * @return $this
     */
    public function setBankLocation($bank_location)
    {
        
        $this->bank_location = $bank_location;
        return $this;
    }
    
    /**
     * Gets bank_name
     * @return string
     */
    public function getBankName()
    {
        return $this->bank_name;
    }
  
    /**
     * Sets bank_name
     * @param string $bank_name 
     * @return $this
     */
    public function setBankName($bank_name)
    {
        
        $this->bank_name = $bank_name;
        return $this;
    }
    
    /**
     * Gets email_notice
     * @return string
     */
    public function getEmailNotice()
    {
        return $this->email_notice;
    }
  
    /**
     * Sets email_notice
     * @param string $email_notice \u662F\u5426\u90AE\u4EF6\u901A\u77E5\u7B7E\u7F72\u4EBA(y/n)
     * @return $this
     */
    public function setEmailNotice($email_notice)
    {
        
        $this->email_notice = $email_notice;
        return $this;
    }
    
    /**
     * Gets linksign_user_id
     * @return string
     */
    public function getLinksignUserId()
    {
        return $this->linksign_user_id;
    }
  
    /**
     * Sets linksign_user_id
     * @param string $linksign_user_id \u9886\u7B7E\u7CFB\u7EDF\u7528\u6237\u7F16\u53F7
     * @return $this
     */
    public function setLinksignUserId($linksign_user_id)
    {
        
        $this->linksign_user_id = $linksign_user_id;
        return $this;
    }
    
    /**
     * Gets person_email
     * @return string
     */
    public function getPersonEmail()
    {
        return $this->person_email;
    }
  
    /**
     * Sets person_email
     * @param string $person_email 
     * @return $this
     */
    public function setPersonEmail($person_email)
    {
        
        $this->person_email = $person_email;
        return $this;
    }
    
    /**
     * Gets person_idcard_image_base64
     * @return string
     */
    public function getPersonIdcardImageBase64()
    {
        return $this->person_idcard_image_base64;
    }
  
    /**
     * Sets person_idcard_image_base64
     * @param string $person_idcard_image_base64 
     * @return $this
     */
    public function setPersonIdcardImageBase64($person_idcard_image_base64)
    {
        
        $this->person_idcard_image_base64 = $person_idcard_image_base64;
        return $this;
    }
    
    /**
     * Gets person_idcard_number
     * @return string
     */
    public function getPersonIdcardNumber()
    {
        return $this->person_idcard_number;
    }
  
    /**
     * Sets person_idcard_number
     * @param string $person_idcard_number 
     * @return $this
     */
    public function setPersonIdcardNumber($person_idcard_number)
    {
        
        $this->person_idcard_number = $person_idcard_number;
        return $this;
    }
    
    /**
     * Gets person_idcard_type
     * @return string
     */
    public function getPersonIdcardType()
    {
        return $this->person_idcard_type;
    }
  
    /**
     * Sets person_idcard_type
     * @param string $person_idcard_type 
     * @return $this
     */
    public function setPersonIdcardType($person_idcard_type)
    {
        
        $this->person_idcard_type = $person_idcard_type;
        return $this;
    }
    
    /**
     * Gets person_name
     * @return string
     */
    public function getPersonName()
    {
        return $this->person_name;
    }
  
    /**
     * Sets person_name
     * @param string $person_name 
     * @return $this
     */
    public function setPersonName($person_name)
    {
        
        $this->person_name = $person_name;
        return $this;
    }
    
    /**
     * Gets person_org_name
     * @return string
     */
    public function getPersonOrgName()
    {
        return $this->person_org_name;
    }
  
    /**
     * Sets person_org_name
     * @param string $person_org_name 
     * @return $this
     */
    public function setPersonOrgName($person_org_name)
    {
        
        $this->person_org_name = $person_org_name;
        return $this;
    }
    
    /**
     * Gets person_phone
     * @return string
     */
    public function getPersonPhone()
    {
        return $this->person_phone;
    }
  
    /**
     * Sets person_phone
     * @param string $person_phone 
     * @return $this
     */
    public function setPersonPhone($person_phone)
    {
        
        $this->person_phone = $person_phone;
        return $this;
    }
    
    /**
     * Gets recipient_index
     * @return string
     */
    public function getRecipientIndex()
    {
        return $this->recipient_index;
    }
  
    /**
     * Sets recipient_index
     * @param string $recipient_index \u4E2A\u4EBA\u7D22\u5F15
     * @return $this
     */
    public function setRecipientIndex($recipient_index)
    {
        
        $this->recipient_index = $recipient_index;
        return $this;
    }
    
    /**
     * Gets signature_image_base64
     * @return string
     */
    public function getSignatureImageBase64()
    {
        return $this->signature_image_base64;
    }
  
    /**
     * Sets signature_image_base64
     * @param string $signature_image_base64 The original signature (scan)
     * @return $this
     */
    public function setSignatureImageBase64($signature_image_base64)
    {
        
        $this->signature_image_base64 = $signature_image_base64;
        return $this;
    }
    
    /**
     * Gets sms_notice
     * @return string
     */
    public function getSmsNotice()
    {
        return $this->sms_notice;
    }
  
    /**
     * Sets sms_notice
     * @param string $sms_notice \u662F\u5426\u77ED\u4FE1\u901A\u77E5\u7B7E\u7F72\u4EBA(y/n)
     * @return $this
     */
    public function setSmsNotice($sms_notice)
    {
        
        $this->sms_notice = $sms_notice;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
