<?php
/**
 * PersonAuthSummary
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * PersonAuthSummary Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PersonAuthSummary implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'banking_status' => 'string',
        'person_id' => 'string',
        'redirect_uri' => 'string',
        'wechat_status' => 'string'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'banking_status' => 'bankingStatus',
        'person_id' => 'personId',
        'redirect_uri' => 'redirectUri',
        'wechat_status' => 'wechatStatus'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'banking_status' => 'setBankingStatus',
        'person_id' => 'setPersonId',
        'redirect_uri' => 'setRedirectUri',
        'wechat_status' => 'setWechatStatus'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'banking_status' => 'getBankingStatus',
        'person_id' => 'getPersonId',
        'redirect_uri' => 'getRedirectUri',
        'wechat_status' => 'getWechatStatus'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $banking_status pending/fail/success
      * @var string
      */
    protected $banking_status;
    
    /**
      * $person_id 
      * @var string
      */
    protected $person_id;
    
    /**
      * $redirect_uri 
      * @var string
      */
    protected $redirect_uri;
    
    /**
      * $wechat_status pending/fail/success
      * @var string
      */
    protected $wechat_status;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->banking_status = $data["banking_status"];
            $this->person_id = $data["person_id"];
            $this->redirect_uri = $data["redirect_uri"];
            $this->wechat_status = $data["wechat_status"];
        }
    }
    
    /**
     * Gets banking_status
     * @return string
     */
    public function getBankingStatus()
    {
        return $this->banking_status;
    }
  
    /**
     * Sets banking_status
     * @param string $banking_status pending/fail/success
     * @return $this
     */
    public function setBankingStatus($banking_status)
    {
        
        $this->banking_status = $banking_status;
        return $this;
    }
    
    /**
     * Gets person_id
     * @return string
     */
    public function getPersonId()
    {
        return $this->person_id;
    }
  
    /**
     * Sets person_id
     * @param string $person_id 
     * @return $this
     */
    public function setPersonId($person_id)
    {
        
        $this->person_id = $person_id;
        return $this;
    }
    
    /**
     * Gets redirect_uri
     * @return string
     */
    public function getRedirectUri()
    {
        return $this->redirect_uri;
    }
  
    /**
     * Sets redirect_uri
     * @param string $redirect_uri 
     * @return $this
     */
    public function setRedirectUri($redirect_uri)
    {
        
        $this->redirect_uri = $redirect_uri;
        return $this;
    }
    
    /**
     * Gets wechat_status
     * @return string
     */
    public function getWechatStatus()
    {
        return $this->wechat_status;
    }
  
    /**
     * Sets wechat_status
     * @param string $wechat_status pending/fail/success
     * @return $this
     */
    public function setWechatStatus($wechat_status)
    {
        
        $this->wechat_status = $wechat_status;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
