<?php
/**
 * Seal
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * Seal Class Doc Comment
 *
 * @category    Class
 * @description \u5370\u7AE0\u4FE1\u606F
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Seal implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'company' => '\Swagger\Client\Model\Company',
        'redirect_uri' => 'string',
        'relate_signature_id' => 'string'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'company' => 'Company',
        'redirect_uri' => 'redirectUri',
        'relate_signature_id' => 'relateSignatureId'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'company' => 'setCompany',
        'redirect_uri' => 'setRedirectUri',
        'relate_signature_id' => 'setRelateSignatureId'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'company' => 'getCompany',
        'redirect_uri' => 'getRedirectUri',
        'relate_signature_id' => 'getRelateSignatureId'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $company 
      * @var \Swagger\Client\Model\Company
      */
    protected $company;
    
    /**
      * $redirect_uri \u6536\u96C6\u5B8C\u6210\u540E\u8DF3\u8F6C\u7684\u5E94\u7528URI
      * @var string
      */
    protected $redirect_uri;
    
    /**
      * $relate_signature_id \u4E0E\u5370\u7AE0\u5173\u8054\u7684\u7B7E\u540D\u7F16\u53F7
      * @var string
      */
    protected $relate_signature_id;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->company = $data["company"];
            $this->redirect_uri = $data["redirect_uri"];
            $this->relate_signature_id = $data["relate_signature_id"];
        }
    }
    
    /**
     * Gets company
     * @return \Swagger\Client\Model\Company
     */
    public function getCompany()
    {
        return $this->company;
    }
  
    /**
     * Sets company
     * @param \Swagger\Client\Model\Company $company 
     * @return $this
     */
    public function setCompany($company)
    {
        
        $this->company = $company;
        return $this;
    }
    
    /**
     * Gets redirect_uri
     * @return string
     */
    public function getRedirectUri()
    {
        return $this->redirect_uri;
    }
  
    /**
     * Sets redirect_uri
     * @param string $redirect_uri \u6536\u96C6\u5B8C\u6210\u540E\u8DF3\u8F6C\u7684\u5E94\u7528URI
     * @return $this
     */
    public function setRedirectUri($redirect_uri)
    {
        
        $this->redirect_uri = $redirect_uri;
        return $this;
    }
    
    /**
     * Gets relate_signature_id
     * @return string
     */
    public function getRelateSignatureId()
    {
        return $this->relate_signature_id;
    }
  
    /**
     * Sets relate_signature_id
     * @param string $relate_signature_id \u4E0E\u5370\u7AE0\u5173\u8054\u7684\u7B7E\u540D\u7F16\u53F7
     * @return $this
     */
    public function setRelateSignatureId($relate_signature_id)
    {
        
        $this->relate_signature_id = $relate_signature_id;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
