<?php
/**
 * Signature
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * Signature Class Doc Comment
 *
 * @category    Class
 * @description \u7B7E\u540D
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Signature implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'personal' => '\Swagger\Client\Model\Personal',
        'redirect_uri' => 'string',
        'relate_seal_id' => 'string'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'personal' => 'Personal',
        'redirect_uri' => 'redirectUri',
        'relate_seal_id' => 'relateSealId'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'personal' => 'setPersonal',
        'redirect_uri' => 'setRedirectUri',
        'relate_seal_id' => 'setRelateSealId'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'personal' => 'getPersonal',
        'redirect_uri' => 'getRedirectUri',
        'relate_seal_id' => 'getRelateSealId'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $personal \u4E2A\u4EBA\u4FE1\u606F
      * @var \Swagger\Client\Model\Personal
      */
    protected $personal;
    
    /**
      * $redirect_uri \u6536\u96C6\u5B8C\u6210\u540E\u8DF3\u8F6C\u7684\u5E94\u7528URI
      * @var string
      */
    protected $redirect_uri;
    
    /**
      * $relate_seal_id \u4E0E\u7B7E\u540D\u5173\u8054\u7684\u5370\u7AE0\u7F16\u53F7
      * @var string
      */
    protected $relate_seal_id;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->personal = $data["personal"];
            $this->redirect_uri = $data["redirect_uri"];
            $this->relate_seal_id = $data["relate_seal_id"];
        }
    }
    
    /**
     * Gets personal
     * @return \Swagger\Client\Model\Personal
     */
    public function getPersonal()
    {
        return $this->personal;
    }
  
    /**
     * Sets personal
     * @param \Swagger\Client\Model\Personal $personal \u4E2A\u4EBA\u4FE1\u606F
     * @return $this
     */
    public function setPersonal($personal)
    {
        
        $this->personal = $personal;
        return $this;
    }
    
    /**
     * Gets redirect_uri
     * @return string
     */
    public function getRedirectUri()
    {
        return $this->redirect_uri;
    }
  
    /**
     * Sets redirect_uri
     * @param string $redirect_uri \u6536\u96C6\u5B8C\u6210\u540E\u8DF3\u8F6C\u7684\u5E94\u7528URI
     * @return $this
     */
    public function setRedirectUri($redirect_uri)
    {
        
        $this->redirect_uri = $redirect_uri;
        return $this;
    }
    
    /**
     * Gets relate_seal_id
     * @return string
     */
    public function getRelateSealId()
    {
        return $this->relate_seal_id;
    }
  
    /**
     * Sets relate_seal_id
     * @param string $relate_seal_id \u4E0E\u7B7E\u540D\u5173\u8054\u7684\u5370\u7AE0\u7F16\u53F7
     * @return $this
     */
    public function setRelateSealId($relate_seal_id)
    {
        
        $this->relate_seal_id = $relate_seal_id;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
