<?php
/**
 * SignatureSummary
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * SignatureSummary Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SignatureSummary implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'signature_file_uri' => 'string',
        'signature_id' => 'string',
        'signer_redirect_uri' => 'string'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'signature_file_uri' => 'signatureFileUri',
        'signature_id' => 'signatureId',
        'signer_redirect_uri' => 'signerRedirectUri'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'signature_file_uri' => 'setSignatureFileUri',
        'signature_id' => 'setSignatureId',
        'signer_redirect_uri' => 'setSignerRedirectUri'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'signature_file_uri' => 'getSignatureFileUri',
        'signature_id' => 'getSignatureId',
        'signer_redirect_uri' => 'getSignerRedirectUri'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $signature_file_uri 
      * @var string
      */
    protected $signature_file_uri;
    
    /**
      * $signature_id 
      * @var string
      */
    protected $signature_id;
    
    /**
      * $signer_redirect_uri 
      * @var string
      */
    protected $signer_redirect_uri;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->signature_file_uri = $data["signature_file_uri"];
            $this->signature_id = $data["signature_id"];
            $this->signer_redirect_uri = $data["signer_redirect_uri"];
        }
    }
    
    /**
     * Gets signature_file_uri
     * @return string
     */
    public function getSignatureFileUri()
    {
        return $this->signature_file_uri;
    }
  
    /**
     * Sets signature_file_uri
     * @param string $signature_file_uri 
     * @return $this
     */
    public function setSignatureFileUri($signature_file_uri)
    {
        
        $this->signature_file_uri = $signature_file_uri;
        return $this;
    }
    
    /**
     * Gets signature_id
     * @return string
     */
    public function getSignatureId()
    {
        return $this->signature_id;
    }
  
    /**
     * Sets signature_id
     * @param string $signature_id 
     * @return $this
     */
    public function setSignatureId($signature_id)
    {
        
        $this->signature_id = $signature_id;
        return $this;
    }
    
    /**
     * Gets signer_redirect_uri
     * @return string
     */
    public function getSignerRedirectUri()
    {
        return $this->signer_redirect_uri;
    }
  
    /**
     * Sets signer_redirect_uri
     * @param string $signer_redirect_uri 
     * @return $this
     */
    public function setSignerRedirectUri($signer_redirect_uri)
    {
        
        $this->signer_redirect_uri = $signer_redirect_uri;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
