<?php
/**
 * Tabs
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2016 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
/**
 * Tabs Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Tabs implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'date_tabs' => '\DateTime[]',
        'sign_here_tabs' => '\Swagger\Client\Model\SignHere[]'
    );
  
    static function swaggerTypes() {
        return self::$swaggerTypes;
    }

    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'date_tabs' => 'dateTabs',
        'sign_here_tabs' => 'signHereTabs'
    );
  
    static function attributeMap() {
        return self::$attributeMap;
    }

    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'date_tabs' => 'setDateTabs',
        'sign_here_tabs' => 'setSignHereTabs'
    );
  
    static function setters() {
        return self::$setters;
    }

    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'date_tabs' => 'getDateTabs',
        'sign_here_tabs' => 'getSignHereTabs'
    );
  
    static function getters() {
        return self::$getters;
    }

    
    /**
      * $date_tabs 
      * @var \DateTime[]
      */
    protected $date_tabs;
    
    /**
      * $sign_here_tabs 
      * @var \Swagger\Client\Model\SignHere[]
      */
    protected $sign_here_tabs;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        
        if ($data != null) {
            $this->date_tabs = $data["date_tabs"];
            $this->sign_here_tabs = $data["sign_here_tabs"];
        }
    }
    
    /**
     * Gets date_tabs
     * @return \DateTime[]
     */
    public function getDateTabs()
    {
        return $this->date_tabs;
    }
  
    /**
     * Sets date_tabs
     * @param \DateTime[] $date_tabs 
     * @return $this
     */
    public function setDateTabs($date_tabs)
    {
        
        $this->date_tabs = $date_tabs;
        return $this;
    }
    
    /**
     * Gets sign_here_tabs
     * @return \Swagger\Client\Model\SignHere[]
     */
    public function getSignHereTabs()
    {
        return $this->sign_here_tabs;
    }
  
    /**
     * Sets sign_here_tabs
     * @param \Swagger\Client\Model\SignHere[] $sign_here_tabs 
     * @return $this
     */
    public function setSignHereTabs($sign_here_tabs)
    {
        
        $this->sign_here_tabs = $sign_here_tabs;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
        }
    }
}
